pipeline {
  agent any
  options { timestamps () }
  stages{
      stage('Build'){
          steps{
              script{
                  def customImage = docker.build("talovadianetomedia/test:${env.BUILD_ID}")
                  customImage.push('kfir')
            }
          }
      }
  }
}